version: "3"

services: 
  mongodb:
    image: mongo
    volumes:
      - ./mongo-db:/data/db
    restart: always

  glode-server:
    image: daniilpdd/glode-server     
    environment:
      - MONGO_URI=mongodb
      - MONGO_PORT=27017
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    restart: always

  mqtt:
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports: 
      - 8000:8000
      - 1884:1884  