version: "3"

services: 
  mongodb:
    image: mongo
    volumes:
      - ./mongo-db:/data/db
    restart: always

  glode-server:
    image: testimg     
    environment:
      - MONGO_URI=mongodb
      - MONGO_PORT=27017
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    restart: always